/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaDeFila;

import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author Aluno
 */
public class Fila extends javax.swing.JFrame {

    /**
     * Creates new form Fila
     */
    //criou uma variavel com a tributo de classe
    private List<String> fila;
    
    public Fila() {
        initComponents();
        //inicialisou a fila
        this.fila = new LinkedList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelChamada = new javax.swing.JLabel();
        labelProximo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cpNome = new javax.swing.JTextField();
        btnIncluirCliente = new javax.swing.JButton();
        btnChamarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        setForeground(new java.awt.Color(102, 255, 51));

        labelChamada.setBackground(new java.awt.Color(255, 0, 0));
        labelChamada.setFont(new java.awt.Font("Arial", 1, 78)); // NOI18N
        labelChamada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelChamada.setText("(chamada)");

        labelProximo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelProximo.setText("Proximo:");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        btnIncluirCliente.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnIncluirCliente.setText("Incluir Cliente");
        btnIncluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirClienteActionPerformed(evt);
            }
        });

        btnChamarCliente.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnChamarCliente.setText("Chamar Cilente");
        btnChamarCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChamarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnChamarCliente)
                .addGap(160, 160, 160))
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelChamada, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProximo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIncluirCliente)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProximo)
                .addGap(18, 18, 18)
                .addComponent(labelChamada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpNome, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIncluirCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChamarCliente)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirClienteActionPerformed
        //criaou a variavel e vinculou ou campo cpNome, .trim sem espaços desnecessários
        String nome = cpNome.getText().trim();
        cpNome.setText("");
        
        //a pessoa foi incluida na fila
        this.fila.add(nome);
    }//GEN-LAST:event_btnIncluirClienteActionPerformed

    private void btnChamarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamarClienteActionPerformed
        //chama o proximo cliente da fila e remove ele
        String nome = this.fila.get(0);
        this.fila.remove(0);
        
        labelChamada.setText(nome);
        
      
        
    
        
        //faz o barulho do bit na hora da chamada
        java.awt.Toolkit.getDefaultToolkit().beep();
    }//GEN-LAST:event_btnChamarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fila().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamarCliente;
    private javax.swing.JButton btnIncluirCliente;
    private javax.swing.JTextField cpNome;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelChamada;
    private javax.swing.JLabel labelProximo;
    // End of variables declaration//GEN-END:variables
}
